version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fantasy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=fantasy_app
    ports:
      - "5432:5432" # Expose for local debugging if needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fantasy_app"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: fantasy_backend
    env_file:
      - ./backend/.env
    environment:
      # Override or set DB connection details to use the 'db' service hostname
      - DATABASE_URL=postgresql://admin:supersecret@db/fantasy_app
    ports:
      - "8000:8000" # Expose for direct API testing
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: fantasy_frontend
    ports:
      - "80:80" # Main entry point for the application
    depends_on:
      - backend

volumes:
  postgres_data: