version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ffa_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ffa-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ffa_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - ffa-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ffa_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - ffa-network
    depends_on:
      - backend

networks:
  ffa-network:
    driver: bridge

volumes:
  postgres_data:
